apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  selector:
    matchLabels:
      app: external-dns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns:latest
        args:
        - --source=service
        - --source=ingress
        - --provider=pdns
        - --pdns-server=http://pdns-extdns-api:9980
        - --pdns-api-key=changeme
        - --txt-owner-id=clusterlab1
        - --domain-filter=pub.jfn.edu
        - --log-level=debug
        - --interval=30s
