apiVersion: v1
kind: Service
metadata:
  name: pdns-extdns-api
  labels:
    app: pdns-extdns-api
spec:
  type: ClusterIP
  ports:
    - port: 9980
      targetPort: 9980
      protocol: TCP
      name: api
  selector:
    app: pdns-extdns
---
apiVersion: v1
kind: Service
metadata:
  name: pdns-extdns-udp
  labels:
    app: pdns-extdns-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: pdns
spec:
  type: LoadBalancer
  loadBalancerIP: 198.51.100.50
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
  selector:
    app: pdns-extdns
---
apiVersion: v1
kind: Service
metadata:
  name: pdns-extdns-tcp
  labels:
    app: pdns-extdns-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: pdns
spec:
  type: LoadBalancer
  loadBalancerIP: 198.51.100.50
  ports:
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
  selector:
    app: pdns-extdns
